// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-rkmjZUm-6TyZHfNL8jjM079FYnqE39o',
    appId: '1:239936566251:web:4e1cc3f7ba138ce4b8dfae',
    messagingSenderId: '239936566251',
    projectId: 'projeto-abastecimento-michel',
    authDomain: 'projeto-abastecimento-michel.firebaseapp.com',
    storageBucket: 'projeto-abastecimento-michel.firebasestorage.app',
    measurementId: 'G-XPF19WCXN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OUzRtUuKUIaJwXKHIm2M7F8pGGb_3Cs',
    appId: '1:239936566251:android:096c4ae301dffbb2b8dfae',
    messagingSenderId: '239936566251',
    projectId: 'projeto-abastecimento-michel',
    storageBucket: 'projeto-abastecimento-michel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcreRXI71U_rgLKkR8F8bQD_YSPCbRiBo',
    appId: '1:239936566251:ios:840cef8fd51a4eaab8dfae',
    messagingSenderId: '239936566251',
    projectId: 'projeto-abastecimento-michel',
    storageBucket: 'projeto-abastecimento-michel.firebasestorage.app',
    iosBundleId: 'br.unigran.projetoAbastecimentoMichel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcreRXI71U_rgLKkR8F8bQD_YSPCbRiBo',
    appId: '1:239936566251:ios:840cef8fd51a4eaab8dfae',
    messagingSenderId: '239936566251',
    projectId: 'projeto-abastecimento-michel',
    storageBucket: 'projeto-abastecimento-michel.firebasestorage.app',
    iosBundleId: 'br.unigran.projetoAbastecimentoMichel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-rkmjZUm-6TyZHfNL8jjM079FYnqE39o',
    appId: '1:239936566251:web:e5d56704bb07b4d3b8dfae',
    messagingSenderId: '239936566251',
    projectId: 'projeto-abastecimento-michel',
    authDomain: 'projeto-abastecimento-michel.firebaseapp.com',
    storageBucket: 'projeto-abastecimento-michel.firebasestorage.app',
    measurementId: 'G-77H96286M1',
  );
}
